### ISSUE TITLE
小白（本人）复刻时产生的一些小问题

### ISSUE THREAD

**Issue by manonbattlefield** [colourfate/thermal_bridge#1]
作者您好，首先感谢您的无私开源！我在复刻这个双目夜视仪时遇到了一些小问题，可能也是像我一样的小白们在复刻时产生的疑问，在此列出。

1、您的最新release中有两个格式的固件，bin和elf，这两个固件都需要烧进去吗？

2、我成功烧录了bin固件，但软件中未能正确出现图像：
![2](https://github.com/colourfate/thermal_bridge/assets/108753304/c48bde77-231e-42d9-a2bb-5b6e4d0aac83)
如果固件烧录没有问题，此时需要检查哪里？

3、手机设置中没有找到otg功能的开关，只有usb调试功能与hdb功能的开关，是否需要都打开？
![1](https://github.com/colourfate/thermal_bridge/assets/108753304/324ebae1-2fef-4875-921b-6b3925019309)

4、手机识别到了这个设备，但显示仅充电，要如何解决？
![3](https://github.com/colourfate/thermal_bridge/assets/108753304/5cffc028-04b7-44e9-ba4c-a555fab23dc4)

期待您的解惑！祝开发顺利！

**Comment by colourfate** [comment]
1. 只用烧写bin文件
2. 确认手机是否有两次弹窗请求连接到USB设备，一次是STM32 Virtual Com，一次是USB Camera，如果有都选择允许，并自动打开应用
3. 不需要修改usb设置，hdb应该是华为手机？没有在鸿蒙上面测试，不确定是否能用
4. 本项目基于UVCAndroid，请测试这个项目中的Release App是否能正常打开USB Camera，如果不行则不支持：https://github.com/shiyinghan/UVCAndroid
5. 直接将设备连接到电脑，正常情况电脑应该识别到两个设备，一个USB Camera，用自带的相机应用应该可以打开，另一个是STM32虚拟串口，用串口助手打开，此时应该可以看到有16进制打印

**Comment by manonbattlefield** [comment]
感谢解答。
我用同学的一加手机测试了下，他的安卓系统可以正常识别两个usb设备
